image: node:latest

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules

install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

testing:
  stage: test
  script:
    - node_modules/gulp/bin/gulp.js --gulpfile ./gulpfile.js default
    - make test-coveralls

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r * .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master

merge_test:
  stage: test
  script:
    - node_modules/gulp/bin/gulp.js --gulpfile ./gulpfile.js default
    - make test-coveralls
  only:
    - merge_requests
