image: node:latest

cache:
  paths:
    - node_modules

before_script:
  - npm install

test:
  script:
    - node_modules/gulp/bin/gulp.js --gulpfile ./gulpfile.js default
  except:
    - master

pages:
  script:
    - mkdir .public
    - cp -r * .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
