image: node:latest

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules

install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

testing:
  stage: test
  script:
    - node_modules/gulp/bin/gulp.js --gulpfile ./gulpfile.js default
    paths:
      - coverage/

merge_test:
  stage: test
  script:
    - node_modules/gulp/bin/gulp.js --gulpfile ./gulpfile.js default
  only:
    - merge_requests

pages:
  stage: deploy
  script:
    - mkdir public/coverage/
    - mv coverage/ public/coverage/
  artifacts:
    paths:
      - public
  only:
    - master
