image: node:latest

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install -g gulp nyc
    - npm install coveralls
    - npm install
  artifacts:
    paths:
      - node_modules/

testing:
  stage: test
  script:
    - npx nyc gulp test
    - npx nyc report --reporter=html
    - npx nyc report --reporter=text-lcov | npx ./node_modules/coveralls/bin/coveralls.js
  artifacts:
    paths:
      - public
      - coverage
      - .nyc_output

merge_test:
  stage: test
  script:
    - npx nyc gulp test
    - npx nyc report --reporter=html
    - npx nyc report --reporter=text-lcov | npx ./node_modules/coveralls/bin/coveralls.js
  only:
    - merge_requests

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r * .public
    - mv .public public
    - mv coverage/ public/coverage/
  artifacts:
    paths:
      - public
  only:
    - master
