# https://www.appveyor.com/docs/appveyor-yml
# https://www.appveyor.com/docs/lang/nodejs-iojs

environment:
  matrix:
    # node.js
    - nodejs_version: "8"
    - nodejs_version: "9"
    - nodejs_version: "10"
    - nodejs_version: "11"
    - nodejs_version: "12"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g gulp 
  - npm install

test_script:
  - node --version
  - npm --version
  - gulp --version
  - cmd: gulp default

build: off

# build version format
version: "{build}"
